### ISSUE TITLE
Torch not loading cltorch

### ISSUE THREAD

**Issue by Dwood15** [hughperkins/cltorch#14]
For some reason, torch isn't loading cltorch, no other info, just "could not load cltorch, skipping"

**Comment by hughperkins** [comment]
Hmmm, you mean, when you do `require 'cltorch'`, you see this message?

If so, can you run the following, and send me the entire output please:

```
git clone --recursive https://github.com/hughperkins/cltorch.git
cd cltorch
luarocks make rocks/cltorch-scm-1.rockspec
```

**Comment by Dwood15** [comment]
user@redlightning:~$ git clone --recursive
https://github.com/hughperkins/cltorch.git
Cloning into 'cltorch'...
remote: Counting objects: 3491, done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 3491 (delta 74), reused 0 (delta 0), pack-reused 3370
Receiving objects: 100% (3491/3491), 789.13 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2336/2336), done.
Checking connectivity... done.
Submodule 'src/EasyCL' (https://github.com/hughperkins/EasyCL.git)
registered for path 'src/EasyCL'
Submodule 'src/clMathLibraries/clBLAS' (
https://github.com/hughperkins/clBLAS) registered for path
'src/clMathLibraries/clBLAS'
Cloning into 'src/EasyCL'...
remote: Counting objects: 1362, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 1362 (delta 7), reused 0 (delta 0), pack-reused 1339
Receiving objects: 100% (1362/1362), 725.46 KiB | 0 bytes/s, done.
Resolving deltas: 100% (870/870), done.
Checking connectivity... done.
Submodule path 'src/EasyCL': checked out
'd74c3bd805f17251a070c1a7fe14f0c2e16cd5ba'
Submodule 'thirdparty/clew' (https://github.com/hughperkins/clew.git)
registered for path 'thirdparty/clew'
Cloning into 'thirdparty/clew'...
remote: Counting objects: 215, done.
remote: Total 215 (delta 0), reused 0 (delta 0), pack-reused 215
Receiving objects: 100% (215/215), 74.87 KiB | 0 bytes/s, done.
Resolving deltas: 100% (83/83), done.
Checking connectivity... done.
Submodule path 'src/EasyCL/thirdparty/clew': checked out
'1d2752564b6af98d24127cdb2d573d3f9ac98f02'
Cloning into 'src/clMathLibraries/clBLAS'...
remote: Counting objects: 1978, done.
remote: Total 1978 (delta 0), reused 0 (delta 0), pack-reused 1978
Receiving objects: 100% (1978/1978), 1.80 MiB | 1.73 MiB/s, done.
Resolving deltas: 100% (1239/1239), done.
Checking connectivity... done.
Submodule path 'src/clMathLibraries/clBLAS': checked out
'bdaf1f9ef3d97168fdaff4c3ef588feeae72b171'

-----------------

dason@redlightning:~/cltorch$ luarocks make rocks/cltorch-scm-1.rockspec
cmake -E make_directory build && cd build && cmake ..
-DCMAKE_BUILD_TYPE=RelWithDebInfo
-DCMAKE_PREFIX_PATH="/home/dason/torch/install/bin/.."
-DCMAKE_INSTALL_PREFIX="/home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1"
&& make -j$(getconf _NPROCESSORS_ONLN) install

-- Found Torch7 in /home/dason/torch/install
/home/dason/cltorch/build
/home/dason/cltorch
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
Submodule path 'src/EasyCL': checked out
'd74c3bd805f17251a070c1a7fe14f0c2e16cd5ba'
Submodule path 'src/EasyCL/thirdparty/clew': checked out
'1d2752564b6af98d24127cdb2d573d3f9ac98f02'
Submodule path 'src/clMathLibraries/clBLAS': checked out
'bdaf1f9ef3d97168fdaff4c3ef588feeae72b171'
CMAKE_INSTALL_PREFIX /home/dason/torch/install
CMAKE_INSTALL_PREFIX /home/dason/torch/install
CLBLAS_INCLUDE_DIRS
/home/dason/cltorch/src/clMathLibraries/clBLAS/src;/home/dason/cltorch/src/EasyCL/thirdparty/clew/include/proxy-opencl
DEEPCL_LIBRARIES
/home/dason/torch/install/lib/libEasyCL.so;/home/dason/torch/install/lib/libclew.so
git version 2.1.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dason/cltorch/build
[  0%] Built target easycl_delete_stamp
Scanning dependencies of target cltorch_static
[  1%] Building CXX object CMakeFiles/cltorch_static.dir/src/init.cpp.o
Submodule path '../src/EasyCL': checked out
'd74c3bd805f17251a070c1a7fe14f0c2e16cd5ba'
Submodule path '../src/EasyCL/thirdparty/clew': checked out
'1d2752564b6af98d24127cdb2d573d3f9ac98f02'
Submodule path '../src/clMathLibraries/clBLAS': checked out
'bdaf1f9ef3d97168fdaff4c3ef588feeae72b171'
[  1%] Built target git_cltorch_rec
[  3%] Creating directories for 'EasyCL-external'
[  5%] No download step for 'EasyCL-external'
[  6%] No patch step for 'EasyCL-external'
[  8%] No update step for 'EasyCL-external'
[ 10%] Performing configure step for 'EasyCL-external'
loading initial cache file
/home/dason/cltorch/build/EasyCL/tmp/EasyCL-external-cache.cmake
-- Configuring done
-- Generating done
-- Build files have been written to:
/home/dason/cltorch/build/EasyCL/src/EasyCL-external-build
[ 12%] Performing build step for 'EasyCL-external'
[  0%] Built target clew_delete_stamp
[  4%] Creating directories for 'clew-external'
[  8%] No download step for 'clew-external'
[ 13%] No patch step for 'clew-external'
[ 17%] No update step for 'clew-external'
[ 21%] Performing configure step for 'clew-external'
loading initial cache file
/home/dason/cltorch/build/EasyCL/src/EasyCL-external-build/clew/tmp/clew-external-cache.cmake
-- Project source dir = /home/dason/cltorch/src/EasyCL/thirdparty/clew
-- Project build dir =
/home/dason/cltorch/build/EasyCL/src/EasyCL-external-build/clew/src/clew-external-build
-- Configuring done
-- Generating done
-- Build files have been written to:
/home/dason/cltorch/build/EasyCL/src/EasyCL-external-build/clew/src/clew-external-build
[ 26%] Performing build step for 'clew-external'
[100%] Built target clew
[ 30%] Performing install step for 'clew-external'
Linking CXX static library libcltorch.a
[ 24%] Built target cltorch_static
[100%] Built target clew
Install the project...
[ 37%] -- Install configuration: "RelWithDebInfo"
-- Up-to-date: /home/dason/torch/install/lib/libclew.so.1.0.0
-- Up-to-date: /home/dason/torch/install/lib/libclew.so
-- Up-to-date: /home/dason/torch/install/include/clew.h
[ 34%] Completed 'clew-external'
Built target clBLAS-external
[ 34%] Built target clew-external
[ 82%] Built target EasyCL
[100%] Built target gpuinfo
[ 39%] Performing install step for 'EasyCL-external'
[  0%] Built target clew_delete_stamp
[  4%] Creating directories for 'clew-external'
[  8%] No download step for 'clew-external'
[ 13%] [ 17%] No update step for 'clew-external'
No patch step for 'clew-external'
[ 21%] Performing configure step for 'clew-external'
loading initial cache file
/home/dason/cltorch/build/EasyCL/src/EasyCL-external-build/clew/tmp/clew-external-cache.cmake
-- Project source dir = /home/dason/cltorch/src/EasyCL/thirdparty/clew
-- Project build dir =
/home/dason/cltorch/build/EasyCL/src/EasyCL-external-build/clew/src/clew-external-build
-- Configuring done
-- Generating done
-- Build files have been written to:
/home/dason/cltorch/build/EasyCL/src/EasyCL-external-build/clew/src/clew-external-build
[ 26%] Performing build step for 'clew-external'
[100%] Built target clew
[ 30%] Performing install step for 'clew-external'
[100%] Built target clew
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Up-to-date: /home/dason/torch/install/lib/libclew.so.1.0.0
-- Up-to-date: /home/dason/torch/install/lib/libclew.so
-- Up-to-date: /home/dason/torch/install/include/clew.h
[ 34%] Completed 'clew-external'
[ 34%] Built target clew-external
[ 82%] Built target EasyCL
[100%] Built target gpuinfo
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Up-to-date: /home/dason/torch/install/lib/libEasyCL.so
-- Up-to-date: /home/dason/torch/install/include/easycl/deprecated.h
-- Up-to-date: /home/dason/torch/install/include/easycl/EasyCL_export.h
-- Up-to-date: /home/dason/torch/install/include/easycl/CLKernel_structs.h
-- Up-to-date: /home/dason/torch/install/include/easycl/CLArrayInt.h
-- Up-to-date: /home/dason/torch/install/include/easycl/CLArrayFloat.h
-- Up-to-date: /home/dason/torch/install/include/easycl/DeviceInfo.h
-- Up-to-date: /home/dason/torch/install/include/easycl/CLFloatWrapper.h
-- Up-to-date: /home/dason/torch/install/include/easycl/ICLArray.h
-- Up-to-date: /home/dason/torch/install/include/easycl/DevicesInfo.h
-- Up-to-date:
/home/dason/torch/install/include/easycl/platforminfo_helper.h
-- Up-to-date: /home/dason/torch/install/include/easycl/CLKernel.h
-- Up-to-date: /home/dason/torch/install/include/easycl/EasyCL.h
-- Up-to-date: /home/dason/torch/install/include/easycl/CLArray.h
-- Up-to-date: /home/dason/torch/install/include/easycl/deviceinfo_helper.h
-- Up-to-date: /home/dason/torch/install/include/easycl/CLWrapper.h
-- Up-to-date: /home/dason/torch/install/include/easycl/CLIntWrapper.h
-- Up-to-date:
/home/dason/torch/install/include/easycl/CLFloatWrapperConst.h
-- Up-to-date: /home/dason/torch/install/include/easycl/CLUCharWrapper.h
-- Up-to-date:
/home/dason/torch/install/include/easycl/templates/LuaTemplater.h
-- Up-to-date:
/home/dason/torch/install/include/easycl/templates/TemplatedKernel.h
-- Up-to-date: /home/dason/torch/install/include/easycl/util/StatefulTimer.h
-- Up-to-date:
/home/dason/torch/install/include/easycl/util/easycl_stringhelper.h
[ 41%] Completed 'EasyCL-external'
[ 41%] Built target EasyCL-external
[ 86%] Built target THCl
Scanning dependencies of target cltorch
[ 87%] Building CXX object CMakeFiles/cltorch.dir/src/init.cpp.o
Linking CXX shared module libcltorch.so
[100%] Built target cltorch
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing:
/home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lib/libcltorch.so
-- Set runtime path of
"/home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lib/libcltorch.so"
to "$ORIGIN/../lib:/home/dason/torch/install/lib:/opt/OpenBLAS/lib"
-- Installing:
/home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lua/cltorch/init.lua
-- Installing:
/home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lua/cltorch/Tensor.lua
-- Installing:
/home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lua/cltorch/Random.lua
-- Installing:
/home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lua/cltorch/Test.lua
-- Installing:
/home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lua/cltorch/unit_storage.lua
-- Installing:
/home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lua/cltorch/unit_tensor.lua
-- Up-to-date: /home/dason/torch/install/include/THCl/THCl.h
-- Up-to-date: /home/dason/torch/install/include/THCl/THClGeneral.h
-- Up-to-date: /home/dason/torch/install/include/THCl/THClBlas.h
-- Up-to-date: /home/dason/torch/install/include/THCl/THClStorage.h
-- Up-to-date: /home/dason/torch/install/include/THCl/THClStorageCopy.h
-- Up-to-date: /home/dason/torch/install/include/THCl/THClTensor.h
-- Up-to-date: /home/dason/torch/install/include/THCl/THClTensorCopy.h
-- Up-to-date: /home/dason/torch/install/include/THCl/THClTensorMath.h
-- Up-to-date: /home/dason/torch/install/include/THCl/THClApply.h
-- Up-to-date: /home/dason/torch/install/include/THCl/THClReduce.h
-- Up-to-date: /home/dason/torch/install/include/THCl/THClReduceApplyUtils.h
-- Up-to-date: /home/dason/torch/install/include/THCl/THClKernels.h
-- Up-to-date: /home/dason/torch/install/include/THCl/THClOperators.h
-- Up-to-date: /home/dason/torch/install/lib/libTHCl.so
cd build
Updating manifest for /home/dason/torch/install/lib/luarocks/rocks
cltorch scm-1 is now built and installed in /home/dason/torch/install/
(license: BSD)

**Comment by Dwood15** [comment]
With that, torch still complains when i do th -l cltorch "could not
load cltorch"


On Wed, Jul 22, 2015 at 9:29 PM, Dwood <dwood15@gmail.com> wrote:
> user@redlightning:~$ git clone --recursive
> https://github.com/hughperkins/cltorch.git
> Cloning into 'cltorch'...
> remote: Counting objects: 3491, done.
> remote: Compressing objects: 100% (121/121), done.
> remote: Total 3491 (delta 74), reused 0 (delta 0), pack-reused 3370
> Receiving objects: 100% (3491/3491), 789.13 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (2336/2336), done.
> Checking connectivity... done.
> Submodule 'src/EasyCL' (https://github.com/hughperkins/EasyCL.git)
> registered for path 'src/EasyCL'
> Submodule 'src/clMathLibraries/clBLAS'
> (https://github.com/hughperkins/clBLAS) registered for path
> 'src/clMathLibraries/clBLAS'
> Cloning into 'src/EasyCL'...
> remote: Counting objects: 1362, done.
> remote: Compressing objects: 100% (23/23), done.
> remote: Total 1362 (delta 7), reused 0 (delta 0), pack-reused 1339
> Receiving objects: 100% (1362/1362), 725.46 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (870/870), done.
> Checking connectivity... done.
> Submodule path 'src/EasyCL': checked out
> 'd74c3bd805f17251a070c1a7fe14f0c2e16cd5ba'
> Submodule 'thirdparty/clew' (https://github.com/hughperkins/clew.git)
> registered for path 'thirdparty/clew'
> Cloning into 'thirdparty/clew'...
> remote: Counting objects: 215, done.
> remote: Total 215 (delta 0), reused 0 (delta 0), pack-reused 215
> Receiving objects: 100% (215/215), 74.87 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (83/83), done.
> Checking connectivity... done.
> Submodule path 'src/EasyCL/thirdparty/clew': checked out
> '1d2752564b6af98d24127cdb2d573d3f9ac98f02'
> Cloning into 'src/clMathLibraries/clBLAS'...
> remote: Counting objects: 1978, done.
> remote: Total 1978 (delta 0), reused 0 (delta 0), pack-reused 1978
> Receiving objects: 100% (1978/1978), 1.80 MiB | 1.73 MiB/s, done.
> Resolving deltas: 100% (1239/1239), done.
> Checking connectivity... done.
> Submodule path 'src/clMathLibraries/clBLAS': checked out
> 'bdaf1f9ef3d97168fdaff4c3ef588feeae72b171'
>
> -----------------
>
> dason@redlightning:~/cltorch$ luarocks make rocks/cltorch-scm-1.rockspec
> cmake -E make_directory build && cd build && cmake ..
> -DCMAKE_BUILD_TYPE=RelWithDebInfo
> -DCMAKE_PREFIX_PATH="/home/dason/torch/install/bin/.."
> -DCMAKE_INSTALL_PREFIX="/home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1"
> && make -j$(getconf _NPROCESSORS_ONLN) install
>
> -- Found Torch7 in /home/dason/torch/install
> /home/dason/cltorch/build
> /home/dason/cltorch
> On branch master
> Your branch is up-to-date with 'origin/master'.
> nothing to commit, working directory clean
> Submodule path 'src/EasyCL': checked out
> 'd74c3bd805f17251a070c1a7fe14f0c2e16cd5ba'
> Submodule path 'src/EasyCL/thirdparty/clew': checked out
> '1d2752564b6af98d24127cdb2d573d3f9ac98f02'
> Submodule path 'src/clMathLibraries/clBLAS': checked out
> 'bdaf1f9ef3d97168fdaff4c3ef588feeae72b171'
> CMAKE_INSTALL_PREFIX /home/dason/torch/install
> CMAKE_INSTALL_PREFIX /home/dason/torch/install
> CLBLAS_INCLUDE_DIRS
> /home/dason/cltorch/src/clMathLibraries/clBLAS/src;/home/dason/cltorch/src/EasyCL/thirdparty/clew/include/proxy-opencl
> DEEPCL_LIBRARIES
> /home/dason/torch/install/lib/libEasyCL.so;/home/dason/torch/install/lib/libclew.so
> git version 2.1.0
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/dason/cltorch/build
> [  0%] Built target easycl_delete_stamp
> Scanning dependencies of target cltorch_static
> [  1%] Building CXX object CMakeFiles/cltorch_static.dir/src/init.cpp.o
> Submodule path '../src/EasyCL': checked out
> 'd74c3bd805f17251a070c1a7fe14f0c2e16cd5ba'
> Submodule path '../src/EasyCL/thirdparty/clew': checked out
> '1d2752564b6af98d24127cdb2d573d3f9ac98f02'
> Submodule path '../src/clMathLibraries/clBLAS': checked out
> 'bdaf1f9ef3d97168fdaff4c3ef588feeae72b171'
> [  1%] Built target git_cltorch_rec
> [  3%] Creating directories for 'EasyCL-external'
> [  5%] No download step for 'EasyCL-external'
> [  6%] No patch step for 'EasyCL-external'
> [  8%] No update step for 'EasyCL-external'
> [ 10%] Performing configure step for 'EasyCL-external'
> loading initial cache file
> /home/dason/cltorch/build/EasyCL/tmp/EasyCL-external-cache.cmake
> -- Configuring done
> -- Generating done
> -- Build files have been written to:
> /home/dason/cltorch/build/EasyCL/src/EasyCL-external-build
> [ 12%] Performing build step for 'EasyCL-external'
> [  0%] Built target clew_delete_stamp
> [  4%] Creating directories for 'clew-external'
> [  8%] No download step for 'clew-external'
> [ 13%] No patch step for 'clew-external'
> [ 17%] No update step for 'clew-external'
> [ 21%] Performing configure step for 'clew-external'
> loading initial cache file
> /home/dason/cltorch/build/EasyCL/src/EasyCL-external-build/clew/tmp/clew-external-cache.cmake
> -- Project source dir = /home/dason/cltorch/src/EasyCL/thirdparty/clew
> -- Project build dir =
> /home/dason/cltorch/build/EasyCL/src/EasyCL-external-build/clew/src/clew-external-build
> -- Configuring done
> -- Generating done
> -- Build files have been written to:
> /home/dason/cltorch/build/EasyCL/src/EasyCL-external-build/clew/src/clew-external-build
> [ 26%] Performing build step for 'clew-external'
> [100%] Built target clew
> [ 30%] Performing install step for 'clew-external'
> Linking CXX static library libcltorch.a
> [ 24%] Built target cltorch_static
> [100%] Built target clew
> Install the project...
> [ 37%] -- Install configuration: "RelWithDebInfo"
> -- Up-to-date: /home/dason/torch/install/lib/libclew.so.1.0.0
> -- Up-to-date: /home/dason/torch/install/lib/libclew.so
> -- Up-to-date: /home/dason/torch/install/include/clew.h
> [ 34%] Completed 'clew-external'
> Built target clBLAS-external
> [ 34%] Built target clew-external
> [ 82%] Built target EasyCL
> [100%] Built target gpuinfo
> [ 39%] Performing install step for 'EasyCL-external'
> [  0%] Built target clew_delete_stamp
> [  4%] Creating directories for 'clew-external'
> [  8%] No download step for 'clew-external'
> [ 13%] [ 17%] No update step for 'clew-external'
> No patch step for 'clew-external'
> [ 21%] Performing configure step for 'clew-external'
> loading initial cache file
> /home/dason/cltorch/build/EasyCL/src/EasyCL-external-build/clew/tmp/clew-external-cache.cmake
> -- Project source dir = /home/dason/cltorch/src/EasyCL/thirdparty/clew
> -- Project build dir =
> /home/dason/cltorch/build/EasyCL/src/EasyCL-external-build/clew/src/clew-external-build
> -- Configuring done
> -- Generating done
> -- Build files have been written to:
> /home/dason/cltorch/build/EasyCL/src/EasyCL-external-build/clew/src/clew-external-build
> [ 26%] Performing build step for 'clew-external'
> [100%] Built target clew
> [ 30%] Performing install step for 'clew-external'
> [100%] Built target clew
> Install the project...
> -- Install configuration: "RelWithDebInfo"
> -- Up-to-date: /home/dason/torch/install/lib/libclew.so.1.0.0
> -- Up-to-date: /home/dason/torch/install/lib/libclew.so
> -- Up-to-date: /home/dason/torch/install/include/clew.h
> [ 34%] Completed 'clew-external'
> [ 34%] Built target clew-external
> [ 82%] Built target EasyCL
> [100%] Built target gpuinfo
> Install the project...
> -- Install configuration: "RelWithDebInfo"
> -- Up-to-date: /home/dason/torch/install/lib/libEasyCL.so
> -- Up-to-date: /home/dason/torch/install/include/easycl/deprecated.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/EasyCL_export.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/CLKernel_structs.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/CLArrayInt.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/CLArrayFloat.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/DeviceInfo.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/CLFloatWrapper.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/ICLArray.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/DevicesInfo.h
> -- Up-to-date:
> /home/dason/torch/install/include/easycl/platforminfo_helper.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/CLKernel.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/EasyCL.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/CLArray.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/deviceinfo_helper.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/CLWrapper.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/CLIntWrapper.h
> -- Up-to-date:
> /home/dason/torch/install/include/easycl/CLFloatWrapperConst.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/CLUCharWrapper.h
> -- Up-to-date:
> /home/dason/torch/install/include/easycl/templates/LuaTemplater.h
> -- Up-to-date:
> /home/dason/torch/install/include/easycl/templates/TemplatedKernel.h
> -- Up-to-date: /home/dason/torch/install/include/easycl/util/StatefulTimer.h
> -- Up-to-date:
> /home/dason/torch/install/include/easycl/util/easycl_stringhelper.h
> [ 41%] Completed 'EasyCL-external'
> [ 41%] Built target EasyCL-external
> [ 86%] Built target THCl
> Scanning dependencies of target cltorch
> [ 87%] Building CXX object CMakeFiles/cltorch.dir/src/init.cpp.o
> Linking CXX shared module libcltorch.so
> [100%] Built target cltorch
> Install the project...
> -- Install configuration: "RelWithDebInfo"
> -- Installing:
> /home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lib/libcltorch.so
> -- Set runtime path of
> "/home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lib/libcltorch.so"
> to "$ORIGIN/../lib:/home/dason/torch/install/lib:/opt/OpenBLAS/lib"
> -- Installing:
> /home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lua/cltorch/init.lua
> -- Installing:
> /home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lua/cltorch/Tensor.lua
> -- Installing:
> /home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lua/cltorch/Random.lua
> -- Installing:
> /home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lua/cltorch/Test.lua
> -- Installing:
> /home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lua/cltorch/unit_storage.lua
> -- Installing:
> /home/dason/torch/install/lib/luarocks/rocks/cltorch/scm-1/lua/cltorch/unit_tensor.lua
> -- Up-to-date: /home/dason/torch/install/include/THCl/THCl.h
> -- Up-to-date: /home/dason/torch/install/include/THCl/THClGeneral.h
> -- Up-to-date: /home/dason/torch/install/include/THCl/THClBlas.h
> -- Up-to-date: /home/dason/torch/install/include/THCl/THClStorage.h
> -- Up-to-date: /home/dason/torch/install/include/THCl/THClStorageCopy.h
> -- Up-to-date: /home/dason/torch/install/include/THCl/THClTensor.h
> -- Up-to-date: /home/dason/torch/install/include/THCl/THClTensorCopy.h
> -- Up-to-date: /home/dason/torch/install/include/THCl/THClTensorMath.h
> -- Up-to-date: /home/dason/torch/install/include/THCl/THClApply.h
> -- Up-to-date: /home/dason/torch/install/include/THCl/THClReduce.h
> -- Up-to-date: /home/dason/torch/install/include/THCl/THClReduceApplyUtils.h
> -- Up-to-date: /home/dason/torch/install/include/THCl/THClKernels.h
> -- Up-to-date: /home/dason/torch/install/include/THCl/THClOperators.h
> -- Up-to-date: /home/dason/torch/install/lib/libTHCl.so
> cd build
> Updating manifest for /home/dason/torch/install/lib/luarocks/rocks
> cltorch scm-1 is now built and installed in /home/dason/torch/install/
> (license: BSD)
>
>



-- 
This message is for the intended recipient(s) only. If you received
this message and you are not the intended recipient, please respond to
notify of the error, and promptly destroy this message.

**Comment by soumith** [comment]
Can you give the log for the command: luajit-l cltorch

**Comment by soumith** [comment]
*
luajit -l cltorch

**Comment by Dwood15** [comment]
I get: luajit: C++ exception


On Wed, Jul 22, 2015 at 10:23 PM, Soumith Chintala <notifications@github.com
> wrote:

> *
> luajit -l cltorch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hughperkins/cltorch/issues/14#issuecomment-123959335>.
>



-- 
This message is for the intended recipient(s) only. If you received this
message and you are not the intended recipient, please respond to notify of
the error, and promptly destroy this message.

**Comment by Dwood15** [comment]
No other information from that command in terminal.

On Wed, Jul 22, 2015 at 10:40 PM, Dwood <dwood15@gmail.com> wrote:

> I get: luajit: C++ exception
>
>
> On Wed, Jul 22, 2015 at 10:23 PM, Soumith Chintala <
> notifications@github.com> wrote:
>
>> *
>> luajit -l cltorch
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hughperkins/cltorch/issues/14#issuecomment-123959335>
>> .
>>
>
>
>
> --
> This message is for the intended recipient(s) only. If you received this
> message and you are not the intended recipient, please respond to notify of
> the error, and promptly destroy this message.
>



-- 
This message is for the intended recipient(s) only. If you received this
message and you are not the intended recipient, please respond to notify of
the error, and promptly destroy this message.

**Comment by hughperkins** [comment]
Hi Dwood15, I've updated cltorch to print the exception message during initialization.  Can you update to the latest version and try again please.  By the way, can you show the output of the `clinfo` command.

**Comment by Dwood15** [comment]
I'll do what I can, though it may be a few days from now.

On Thu, Jul 23, 2015 at 4:14 AM, Hugh Perkins <notifications@github.com>
wrote:

> Hi Dwood15, I've updated cltorch to print the exception message during
> initialization. Can you update to the latest version and try again please.
> By the way, can you show the output of the clinfo command.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hughperkins/cltorch/issues/14#issuecomment-124045564>.
>



-- 
This message is for the intended recipient(s) only. If you received this
message and you are not the intended recipient, please respond to notify of
the error, and promptly destroy this message.

**Comment by hughperkins** [comment]
(Closing since no update since a week or two)
