### ISSUE TITLE
rpath and warnings

### ISSUE THREAD

**Issue by andresy** [hughperkins/cltorch#15]
Hi... when installing the lib, libcltorch.so gets linked with various things (libluaT, libTHCl...), and libclBLAS. Strangely, while all libs are linked with rpath, libclBLAS is not. Any reason for this? [I am running under mac]

Unrelated question: when running (still on mac) the test(), I get a lot of warnings (not critical ones). Does it appear on your development platform?

**Comment by hughperkins** [comment]
I dont have access to a mac... I'm tempted to buy one, just to test the build, but so far have not done so... I think that rpath is a mac-specific concept right?  Again, I have no way of playing with rpath to find out what it is, what it does, how it behaves.  Is fixing the mac build something you might have a moment to look into sometime?

**Comment by andresy** [comment]
Thanks! rpath is unix, but the way it is handled under mac is slightly different than linux. Will look into it, during my spare time :) Should I fix the warnings, too?

Note: except the "libblas not found" (because of rpath) issue, it works like a charm under mac.

**Comment by hughperkins** [comment]
Ok.  What warnings are you getting?  By the way, just to check, there are no legal ways for me to run Mac OS X in a vm, is that right?  Or to at least set up an identical build/clang environment?

**Comment by hughperkins** [comment]
By the way, I finally found a way of building stuff on Mac :-)  I'm only building DeepCL for now, but the method seems generally applicable https://travis-ci.org/hughperkins/homebrew-test-travis-osx/builds/93269984

**Comment by hughperkins** [comment]
Quick update: found that travis can natively build mac os x projects, quite easily in fact, and set up a travis for deepcl at https://travis-ci.org/hughperkins/DeepCL/builds  .  A lot of build warnings should have disappeared now I think?

**Comment by hughperkins** [comment]
Hmmm, wrong library, deleted prevoius comment :-P  though I am gradually working on adding unit tests for cltorch travis build too... https://travis-ci.org/hughperkins/cltorch/builds/100137705

**Comment by hughperkins** [comment]
Build on mac works ok now https://travis-ci.org/hughperkins/cltorch

=> closing.
