### ISSUE TITLE
Test failed: could not load cltorch, skipping

### ISSUE THREAD

**Issue by sorrge** [hughperkins/cltorch#18]
Hi,

I've installed cltorch as described here: https://github.com/hughperkins/cltorch
During "luarocks make rocks/cltorch-scm-1.rockspec", I had a lot of warnings but no error message. The last line says "cltorch scm-1 is now built and installed in <my torch install folder> (license: BSD)"

However, when I run "th -l cltorch -e 'cltorch.test()'" afterwards, it says:
could not load cltorch, skipping
[string "cltorch.test()"]:1: attempt to index global 'cltorch' (a nil value)

**Comment by szagoruyko** [comment]
have the same problem on a new macbook

**Comment by hughperkins** [comment]
Hi, if you install the latest version of 'new-easycl' branch, and install that, how well does that work?  ie:

```
git clone --recursive https://github.com/hughperkins/cltorch.git -b new-easycl
cd cltorch
luarocks make rocks/cltorch-scm-1.rockspec
th -l cltorch -e 'a = torch.ClTensor({3,5,2}); print(a); print(a+2)"
```

**Comment by sorrge** [comment]
Tried it (without uninstalling the original cltorch, should I?). I have the same result: "could not load cltorch, skipping" and then "attempt to call field 'ClTensor' (a nil value)". I am also on a Mac, BTW. Is there some kind of debug mode that will show more information than just "could not load"?

**Comment by hughperkins** [comment]
Ah, fair enough.  Out of ideas for now.  If nothing else comes up, I might need remote access to one of your macs ideally, eg using TeamViewer or similar (TeamViewer lets you see what I'm doing whilst I'm doing it).

> BTW. Is there some kind of debug mode that will show more information than just "could not load"?

You can use `luajit` instead of `th`.   If that's still not sufficiently detailed, need to use gdb to run luajit.

**Comment by hughperkins** [comment]
Hi.  I think I'd like to see two things:
- full output of running ```cd ~/torch; ./install.sh```
- full output of the cltorch installation

No need to uninstall either of these first.  I just want to see what things are failing in these.  eg, I suspect maybe gfortran or similar might be missing.

**Comment by szagoruyko** [comment]
adding
```bash
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:~/torch/install/lib
```
to `.bash_profile` solved the problem

**Comment by sorrge** [comment]
Thanks! That works. An update to the installation instructions would be nice.

**Comment by hughperkins** [comment]
Hmmm, is that not already part of [torch_activate](https://github.com/torch/distro/blob/master/install.sh#L122-L127)?  However, I shall update the instructions for cltorch to mention this point.

**Comment by hughperkins** [comment]
Edit: by the way, glad it works.  Thank-you very much Sergey for solving this :-)

**Comment by hughperkins** [comment]
Seems like this can be closed, right?
