### ISSUE TITLE
th -l cltorch cannot load libcltorch.so but luajit -l cltorch works

### ISSUE THREAD

**Issue by Jovp** [hughperkins/cltorch#31]
Hi,

First I must say that I am really new to torch, lua etc.
I am currently trying to install and use cltorch.
Apprently the installation went right, but as I am trying to use cltorch with th it does not work and it raises "cannot load libcltorch.so" such as mentioned in : 
https://github.com/hughperkins/cltorch/issues/5
and https://github.com/hughperkins/cltorch/issues/24
The thing is I am using the mac os Shell (I am on OSX El Capitan) and so the solutions proposed do not seem to be linked to my issue.
In another thread I saw the "luajit -l cltorch" command come out and tried it.
It seems to start another instance of torch than "th" and wen I do th> c = torch.ClTensor{7,4,5} it seems to work well as I get : 
"Using Apple , OpenCL platform: Apple
Using OpenCL device: Iris"

Do you have any idea on how I can make it work ?
Thanks

**Comment by hughperkins** [comment]
Did you try removing the first line of the `th` script, as per https://github.com/hughperkins/cltorch/issues/21

**Comment by Jovp** [comment]
Oh,
Thank you very much, I feel so stupid right now, didn't see the post...

**Comment by hughperkins** [comment]
Ah, cool :-)  We should fix that issue somehow sometime really.

**Comment by tigerneil** [comment]
Hey, spend one day on this confused problem. FINALLY I fix it by switch back to bash shell. I used zsh before, can't properly load some path. @hughperkins thanks for your explanation. 
What a mysterious situation!
```
th> require 'cltorch'
{
  finish : function: 0x027e2608
  about : function: 0x0241a4a8
  getDeviceCount : function: 0x027e2720
  setAllowNonGpus : function: 0x02821cc0
  getDeviceProperties : function: 0x027e2778
  getState : function: 0x027e27c8
  test : function: 0x028091a0
  setEnableTiming : function: 0x027e26a8
  _state : userdata: 0x7fbe6bd14310
  getDevice : function: 0x02821d48
  dumpProfiling : function: 0x0241a460
  setTrace : function: 0x027e2818
  setAddFinish : function: 0x027e29f0
  setDevice : function: 0x02821d98
  synchronize : function: 0x02821e28
  dumpTimings : function: 0x02821de8
  setProfiling : function: 0x027e2658
  setTiming : function: 0x0241a410
  setDetailedTimings : function: 0x027e26d0
}

```

**Comment by prlz77** [comment]
@hughperkins thank you so much. @tigerneil same as you. I switched to bash. I recommend you to extend bash with bash-it in exchange for zsh.
