### ISSUE TITLE
googlenet benchmark in convnet-benchmarks fails with SpatialAveragePooling error

### ISSUE THREAD

**Issue by manjunaths** [hughperkins/cltorch#41]
Hello,
I am trying to run the convnet benchmarks with cltorch. The 3 benchmarks alexnet, overfeat and vgg_a runs.
But Googlenet fails with the below error. I've installed clnn and nn. Can you please help ?

[blah@what-15 cltorch]$ th imagenet_winners/benchmark.lua
libthclnn_searchpath    /usr2/blah/Moonshot/DeepLearning/torch/install/lib/lua/5.1/libTHCLNN.so
Running on device: Intel(R) HD Graphics
/usr2/blah/Moonshot/DeepLearning/torch/install/bin/luajit: ./imagenet_winners/googlenet.lua:54: attempt to call local 'SpatialAveragePooling' (a nil value)
stack traceback:
        ./imagenet_winners/googlenet.lua:54: in function <./imagenet_winners/googlenet.lua:30>
        imagenet_winners/benchmark.lua:34: in main chunk
        [C]: in function 'dofile'
        ...ning/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x004058d0

Thanks.

**Comment by hughperkins** [comment]
Hmmm.  Can you please update all the following, and confirm you do/dont still have an issue please?

```
luarocks install nn
luarocks install cltorch
luarocks install clnn
```

Also, can you provide the output of the following please? (after updating)

```
luajit -l cltorch -e 'cltorch.about()'
luajit -l clnn -e 'clnn.about()'
```

**Comment by manjunaths** [comment]
I installed all of them again as you instructed and ran the commands. Here is the output.

[blah@what-15 cltorch]$ luajit -l cltorch -e 'cltorch.about()'
cltorch.  OpenCL backend for Torch
Built from commit 378aaf7
More info, doc: https://github.com/hughperkins/cltorch
Issues: https://github.com/hughperkins/cltorch/issues

[blah@what-15 cltorch]$ luajit -l clnn -e 'clnn.about()'
libthclnn_searchpath    /usr2/blah/Moonshot/DeepLearning/torch/install/lib/lua/5.1/libTHCLNN.so
clnn.  OpenCL backend for Torch nn
Built from commit
More info, doc: https://github.com/hughperkins/clnn
Issues: https://github.com/hughperkins/clnn/issues

Thank you.

**Comment by manjunaths** [comment]
I changed the line in googlenet.lua in convnet benchmarks to local SpatialAveragePooling = nn.SpatialAveragePooling 

and it seems to be running. I will get back if there are anymore issues. 

Thanks for the support.

**Comment by hughperkins** [comment]
Ah great!  Cool! :-)
