### ISSUE TITLE
Tons of errors on Arch using "cltorch.test"

### ISSUE THREAD

**Issue by beezdul** [hughperkins/cltorch#45]
Here's a pastebin link to the output of  luajit -l cltorch -e 'cltorch.test()'
http://pastebin.com/05120uGR

Here's some errors that happen when running "luarocks install cltorch":

[ 65%] Building CXX object src/lib/CMakeFiles/THCl.dir/THClTensorMathBlas.cpp.o
In file included from /tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClApply.h:7:0,
                 from /tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClApply.cpp:1:
/tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClReduceApplyUtils.h: In instantiation of ‘TensorInfo<IndexType>::TensorInfo(THClState*, THClTensor*, int) [with IndexType = long long unsigned int; THClState = THClState; THClTensor = THClTensor]’:
/tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClApply.cpp:216:58:   required from here
/tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClReduceApplyUtils.h:155:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (strideOuter == sizes[collapsedIndex] * strides[collapsedIndex]) {
                     ^
[ 67%] Building CXX object src/lib/CMakeFiles/THCl.dir/THClReduce.cpp.o
[ 68%] Building CXX object src/lib/CMakeFiles/THCl.dir/THClTypeParseTraits.cpp.o
[ 70%] Building CXX object src/lib/CMakeFiles/THCl.dir/THClReduceAll.cpp.o
[ 72%] Building CXX object src/lib/CMakeFiles/THCl.dir/THClDeviceUtils.cpp.o
[ 73%] Building CXX object src/lib/CMakeFiles/THCl.dir/THClTensorMasked.cpp.o
[ 75%] Building CXX object src/lib/CMakeFiles/THCl.dir/THClTensorMathTransformReduce.cpp.o
[ 77%] Building CXX object src/lib/CMakeFiles/THCl.dir/THClTensorIndex.cpp.o
[ 78%] Building CXX object src/lib/CMakeFiles/THCl.dir/THClKernels.cpp.o
In file included from /tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClReduce.h:9:0,
                 from /tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClReduce.cpp:3:
/tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClReduceApplyUtils.h: In instantiation of ‘TensorInfo<IndexType>::TensorInfo(THClState*, THClTensor*, int) [with IndexType = long long unsigned int; THClState = THClState; THClTensor = THClTensor]’:
/tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClReduce.cpp:278:42:   required from here
/tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClReduceApplyUtils.h:155:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (strideOuter == sizes[collapsedIndex] * strides[collapsedIndex]) {
                     ^
[ 80%] Building CXX object src/lib/CMakeFiles/THCl.dir/THClTensorMathScan.cpp.o
[ 81%] Building CXX object src/lib/CMakeFiles/THCl.dir/THClGather.cpp.o
In file included from /tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClKernels.h:11:0,
                 from /tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClReduceAll.cpp:1:
/tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClReduceApplyUtils.h: In instantiation of ‘TensorInfo<IndexType>::TensorInfo(THClState*, THClTensor*, int) [with IndexType = long long unsigned int; THClState = THClState; THClTensor = THClTensor]’:
/tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClReduceAll.cpp:310:40:   required from here
/tmp/luarocks_cltorch-scm-1-561/cltorch/cltorch/src/lib/THClReduceApplyUtils.h:155:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (strideOuter == sizes[collapsedIndex] * strides[collapsedIndex]) {
                     ^
[ 83%] Building CXX object src/lib/CMakeFiles/THCl.dir/THClScatter.cpp.o
[ 85%] Linking CXX shared library libTHCl.so
[ 85%] Built target THCl

**Comment by beezdul** [comment]
Okay so the problem is that I was using mesa instead of catalyst.

**Comment by hughperkins** [comment]
Ok, cool :-)
