### ISSUE TITLE
Problem running the tests

### ISSUE THREAD

**Issue by luan-cestari** [hughperkins/cltorch#49]
Hi,

I was trying to use CLTorch but, after the installation, all the tests failed. I'm using an AMD Radeon R9 390 which I think the Mesa OpenCL implementation is not stable/complete as the first error states this `input.cl:8:1: error: OpenCL does not support the 'static' storage class specifier` (also someone mentioned this these days on http://www.diybookscanner.org/forum/viewtopic.php?f=21&t=3195&start=210 ). I made this gist ( https://gist.github.com/luan-cestari/494cbae6a3586be94402 ) with the complete output. I will be please if anyone have a hint how to solve it or , please, let me know if I could contribute to solve it as well =)

Thank in advance

Luan

**Comment by hughperkins** [comment]
Hi luan-cestari,

You're using OpenCL 1.1, which is sort of borderline for my supporting it.  1.2 is what I have been developing against recently.

To fix your problem in a hacky way, without modifying upstream, I think what you can try doing is open the following lines, and remove all the `inline` words, and then recompile:
- src/lib/THClReduceApplyUtils.cl
- src/lib/THClReduceAll.cl
- src/lib/THClDeviceUtils.cl
- ...maybe others

If it was me, I might try simply:
```
sed -i -e 's/inline //g' src/lib/*.cl
```
This will probably give you build warnings, about missing a declaration, but might compile.  If that doesnt work, you could try:
```
git checkout src/lib/*.cl
sed -i -e 's/inline /static inline /g' src/lib/*.cl
```
Or:
```
git checkout src/lib/*.cl
sed -i -e 's/inline /static /g' src/lib/*.cl
```
(And recompile + retest each time).

That's a hacky fix, that doesnt modify upstream.  That's probably a good place to start for now.

**Comment by luan-cestari** [comment]
Thank you very much :D I am trying to use the amd driver and sdk to get
opencl 1.2 /2.0 . The mesa opencl library seems to be pretty outdated and
amd is not very friendly on linux (it seems that I will have to downgrade
my xorg to make it work).

Thank you again for your kind help and quickly reply

Kind regards
Luan

**Comment by hughperkins** [comment]
Ok.  What OS are you using?  If you are using Ubuntu 14.04, does Ubuntu 15.10 have more recent drivers? (I'm not saying it does, just curious).

**Comment by luan-cestari** [comment]
Hi,

I am using fedora 23, which doesn't have the proprietary driver working, so
I'm using the open source version (which is reversed engineered) and relies
on Mesa with an extension for OpenCL 1.1 implementation (it is very old and
doesn't have any plan to implement OpenCL 1.2 or 2 ). I tried to get the
amd driver to work but got many problems, I created a thread on amd
official forum to seem if I get any help with that
https://community.amd.com/thread/197532 . I really hope AMD help to figure
out this, specially that they  open sourced even the proprietary driver
recently. I'm also thinking to use windows just to try out some experiments
with cltorch =)


Thank you for your help and advices


Kind regards,

Luan

**Comment by hughperkins** [comment]
Ah.... well... sounds good.  Is there anything you need from me at the moment?  Sounds like it's mostly a question of somehow getting the drivers working, for now?

**Comment by sureshaHospet** [comment]
Dear Sir,

I'm using Kali-linux rolling

I'm trying a crack a WPA/WPA2 PSK passphrase using below command
hashcat -m 2500 airCrack_outFile.hccap psk_cracking_Dictionary.txt

Am getting a error msg as 

Initializing device kernels and memory...clBuildProgram(): CL_BUILD_PROGRAM_FAILURE

input.cl:20:1: error: OpenCL version 1.1 does not support the 'static' storage class specifier
input.cl:118:1: error: OpenCL version 1.1 does not support the 'static' storage class specifier
input.cl:169:1: error: OpenCL version 1.1 does not support the 'static' storage class specifier
input.cl:203:1: error: OpenCL version 1.1 does not support the 'static' storage class specifier
input.cl:331:1: error: OpenCL version 1.1 does not support the 'static' storage class specifier
input.cl:384:1: error: OpenCL version 1.1 does not support the 'static' storage class specifier
input.cl:420:1: error: OpenCL version 1.1 does not support the 'static' storage class specifier
input.cl:548:1: error: OpenCL version 1.1 does not support the 'static' storage class specifier

* Device #1: Kernel /usr/local/share/hashcat/OpenCL/m02500.cl build failure. Proceeding without this device.

I've updated opencl package using below commnd
apt-get install amd-opencl-dev

Still I'm facing issue.

Can anyone please help me on this regard.

Thanks in Advance for your valuable help
