### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by rayset** [hughperkins/cltorch#51]
when I input
`      sudo apt-get Makefile`
I get, after a while, this error

```
      -- Installing: /home/ubuntu/torch/install/bin/easycl_activate.sh
[ 26%] Completed 'EasyCL-external'
[ 26%] Built target EasyCL-external
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.
```

If anyone could help me it would be great.

I am running ubuntu, fresh install. I do have torch.

**Comment by rayset** [comment]
seems like running sudo apt-get install gfortran

fixes it. I am not really into linux, but I guess this is a missing dependency? I will leave this open for a bit, hope this helps anyone else with this problem.

**Comment by hughperkins** [comment]
Ah.... right.... yes :-)

**Comment by hughperkins** [comment]
Added to README just in case :-)   88334bc
