### ISSUE TITLE
allow cpu backend

### ISSUE THREAD

**Issue by LorenzoBoccaccia** [hughperkins/cltorch#55]
can cpu backend be allowed for testing purposes?

it could be useful if this ran on Intel OpenCL:

```
Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 1.2 LINUX
  Platform Name:                                 Intel(R) OpenCL
  Platform Vendor:                               Intel(R) Corporation
  Platform Extensions:                           cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_fp64


  Platform Name:                                 Intel(R) OpenCL
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_CPU

```

**Comment by LorenzoBoccaccia** [comment]
nvm I downloaded it all and changed the default, some tests aren't passing tho

**Comment by hughperkins** [comment]
Yeah, it's non-trivial to get gpu things to run on the 'cpu' part of a cpu.  You can get it to run on the integrated graphics of a cpu, and modern Intel and AMD cpus both have these.  But you'll struggle to make it run on any cpu with less than about ~32-64 cores.  You can probably buy a nice Titan X for the cost of a 32 core processor :-P  And note, that doenst mean four 8-core procs: it would have to be one single 32-core proc :-P

**Comment by hughperkins** [comment]
So, I'm going to close this, ok?
