### ISSUE TITLE
torch-activate?

### ISSUE THREAD

**Issue by thistleknot** [hughperkins/cltorch#57]
I seem to be missing torch-activate from my /bin directory

**Comment by hughperkins** [comment]
you mean, from `~/torch/install/bin`?  Its normally because youre' missing `checkarg` and `env` or similar.  Anyway, the contents can be something like https://github.com/ASAPPinc/distro/blob/barebones-install/bat/torch-activate

**Comment by thistleknot** [comment]
I'm trying to follow the instructions listed here https://github.com/hughperkins/cltorch

and it mentions I need to have torch-activate (but I see in your distro I only use that if I have a non standard terminal)

**Comment by thistleknot** [comment]
nm, I see it.  I guess I didn't run ./install.sh

**Comment by hughperkins** [comment]
Ok.  To be honest, you should probably reinstall the standard distro, ie https://github.com/torch/distro.git

**Comment by hughperkins** [comment]
(though if cltorch works with the slimmed down distro, that would be interesting information.  I made that distro for non-gpu, cpu-only training though; never tested it on any form of gpu.  probably will work though.  I think)
