### ISSUE TITLE
test errors

### ISSUE THREAD

**Issue by thistleknot** [hughperkins/cltorch#58]
running the test
``luajit -l cltorch -e 'cltorch.test()'

I get this report

user@user-H8DG6-H8DGi:~$ luajit -l cltorch -e 'cltorch.test()'
running tests...
aftter requiring cltorch.unit_storage
Running 2 tests
1/2 test_get ............................................................ [WAIT]
1/2 test_get ............................................................ [ERROR]
2/2 test_basic .......................................................... [WAIT]
2/2 test_basic .......................................................... [ERROR]
Completed 0 asserts in 2 tests with 0 failures and 2 errors and 1 warning
--------------------------------------------------------------------------------
test_get
 Function call failed
Something went wrong: OpenCL library not found at /tmp/luarocks_cltorch-scm-1-489/cltorch/cltorch/src/torch/generic/Storage.cpp:101
stack traceback:
	[C]: at 0x7f8569f94620
	[C]: in function 'ClStorage'
	/usr/local/share/lua/5.1/cltorch/unit_storage.lua:64: in function 'v'
	/usr/local/share/lua/5.1/cltorch/unit_storage.lua:84: in function </usr/local/share/lua/5.1/cltorch/unit_storage.lua:82>
	[C]: in function 'xpcall'
	/home/user/torch/install/share/lua/5.1/torch/Tester.lua:476: in function '_pcall'
	/home/user/torch/install/share/lua/5.1/torch/Tester.lua:436: in function '_run'
	/home/user/torch/install/share/lua/5.1/torch/Tester.lua:354: in function 'run'
	/usr/local/share/lua/5.1/cltorch/unit_storage.lua:91: in function 'test'
	/usr/local/share/lua/5.1/cltorch/Test.lua:8: in function 'test'
	(command line):1: in main chunk
	[C]: at 0x00405ea0

--------------------------------------------------------------------------------
test_basic
 Function call failed
No OpenCL-enabled devices available at /tmp/luarocks_cltorch-scm-1-489/cltorch/cltorch/src/lib/THClGeneral.cpp:139
stack traceback:
	[C]: at 0x7f8569f94620
	[C]: in function 'ClStorage'
	/usr/local/share/lua/5.1/cltorch/unit_storage.lua:25: in function 'v'
	/usr/local/share/lua/5.1/cltorch/unit_storage.lua:84: in function </usr/local/share/lua/5.1/cltorch/unit_storage.lua:82>
	[C]: in function 'xpcall'
	/home/user/torch/install/share/lua/5.1/torch/Tester.lua:476: in function '_pcall'
	/home/user/torch/install/share/lua/5.1/torch/Tester.lua:436: in function '_run'
	/home/user/torch/install/share/lua/5.1/torch/Tester.lua:354: in function 'run'
	/usr/local/share/lua/5.1/cltorch/unit_storage.lua:91: in function 'test'
	/usr/local/share/lua/5.1/cltorch/Test.lua:8: in function 'test'
	(command line):1: in main chunk
	[C]: at 0x00405ea0

--------------------------------------------------------------------------------
Should use TestSuite rather than plain lua table

--------------------------------------------------------------------------------
luajit: /home/user/torch/install/share/lua/5.1/torch/Tester.lua:362: An error was found while running tests!
stack traceback:
	[C]: in function 'assert'
	/home/user/torch/install/share/lua/5.1/torch/Tester.lua:362: in function 'run'
	/usr/local/share/lua/5.1/cltorch/unit_storage.lua:91: in function 'test'
	/usr/local/share/lua/5.1/cltorch/Test.lua:8: in function 'test'
	(command line):1: in main chunk
	[C]: at 0x00405ea0

CLInfo does list my AMD card (I installed fglrx as well, I have an r7 200 series card)

user@user-H8DG6-H8DGi:~$ clinfo
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (1729.3)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 

  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 2
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 AMD Radeon R7 200 Series   
  Device Topology:				 PCI[ B#4, D#0, F#0 ]
  Max compute units:				 14
  Max work items dimensions:			 3
    Max work items[0]:				 256
    Max work items[1]:				 256
    Max work items[2]:				 256
  Max work group size:				 256
  Preferred vector width char:			 4
  Preferred vector width short:			 2
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 4
  Native vector width short:			 2
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 1000Mhz
  Address bits:					 64
  Max memory allocation:			 1185153024
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 64
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 2048
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 No
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 1794113536
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 32768
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 1185153024
  Max global variable size:			 1066637568
  Max global variable preferred total size:	 1794113536
  Max read/write image args:			 64
  Max on device events:				 1024
  Queue on device max size:			 524288
  Max on device queues:				 1
  Queue on device preferred size:		 262144
  SVM capabilities:				 
    Coarse grain buffer:			 Yes
    Fine grain buffer:				 Yes
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 64
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 0x7f2f476758f0
  Name:						 Bonaire
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 1729.3 (VM)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 2.0 AMD-APP (1729.3)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_atomic_counters_32 cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images 

  Device Type:					 CL_DEVICE_TYPE_CPU
  Vendor ID:					 1002h
  Board name:					 
  Max compute units:				 32
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 1024
  Max work group size:				 1024
  Preferred vector width char:			 16
  Preferred vector width short:			 8
  Preferred vector width int:			 4
  Preferred vector width long:			 2
  Preferred vector width float:			 8
  Preferred vector width double:		 4
  Native vector width char:			 16
  Native vector width short:			 8
  Native vector width int:			 4
  Native vector width long:			 2
  Native vector width float:			 8
  Native vector width double:			 4
  Max clock frequency:				 2099Mhz
  Address bits:					 64
  Max memory allocation:			 8416726016
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 64
  Max image 2D width:				 8192
  Max image 2D height:				 8192
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 4096
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 33666904064
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Global
  Local memory size:				 32768
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 4121758720
  Max global variable size:			 1879048192
  Max global variable preferred total size:	 1879048192
  Max read/write image args:			 64
  Max on device events:				 0
  Queue on device max size:			 0
  Max on device queues:				 0
  Queue on device preferred size:		 0
  SVM capabilities:				 
    Coarse grain buffer:			 No
    Fine grain buffer:				 No
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 1
  Error correction support:			 0
  Unified memory for Host and Device:		 1
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 Yes
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 No
    Profiling :					 No
  Platform ID:					 0x7f2f476758f0
  Name:						 AMD Opteron(TM) Processor 6272
  Vendor:					 AuthenticAMD
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 1729.3 (sse2,avx,fma4)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 AMD-APP (1729.3)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_spir cl_khr_gl_event

**Comment by hughperkins** [comment]
Yes, it looks like you dont have a GPU installed.  Unfortunately an OpenCL-enabled CPU is not sufficient.  An integrated GPU inside a CPU will work, eg an Intel HD5500, but a CPU, with OpenCL, but no GPU as such wont work.  Sorry :-(

**Comment by thistleknot** [comment]
oh!  Thanks for the clarification! :)
