### ISSUE TITLE
Unit Test Failed - Mac: El Capitan

### ISSUE THREAD

**Issue by jasonmerchant** [hughperkins/cltorch#59]
The test_basic fails for me on my MacBook Pro (13-inch, Early 2015) with Intel Iris Graphics 6100

Please help!

Here is the output of the test:

luajit -l cltorch -e 'cltorch.test()'
running tests...
aftter requiring cltorch.unit_storage
Running 2 tests
1/2 test_get ............................................................ [WAIT]
Using Apple , OpenCL platform: Apple
Using OpenCL device: Intel(R) Iris(TM) Graphics 6100
1/2 test_get ............................................................ [PASS]
2/2 test_basic .......................................................... [WAIT]
2/2 test_basic .......................................................... [ERROR]
Completed 4 asserts in 2 tests with 0 failures and 1 error and 1 warning
--------------------------------------------------------------------------------
test_basic
 Function call failed
... jason/torch/install/share/lua/5.1/torch/Tester.lua:85: message parameter must be a string
stack traceback:
	[C]: in function 'assert'
	... jason/torch/install/share/lua/5.1/torch/Tester.lua:85: in function 'getMessage'
	... jason/torch/install/share/lua/5.1/torch/Tester.lua:199: in function 'asserteq'
	... jason/torch/install/share/lua/5.1/cltorch/unit_storage.lua:25: in function 'v'
	... jason/torch/install/share/lua/5.1/cltorch/unit_storage.lua:84: in function <...ant/torch/install/share/lua/5.1/cltorch/unit_storage.lua:82>
	[C]: in function 'xpcall'
	... jason/torch/install/share/lua/5.1/torch/Tester.lua:476: in function '_pcall'
	... jason/torch/install/share/lua/5.1/torch/Tester.lua:436: in function '_run'
	... jason/torch/install/share/lua/5.1/torch/Tester.lua:354: in function 'run'
	... jason/torch/install/share/lua/5.1/cltorch/unit_storage.lua:91: in function 'test'
	... jason/torch/install/share/lua/5.1/cltorch/Test.lua:8: in function 'test'
	(command line):1: in main chunk
	[C]: at 0x0102fc4bb0

--------------------------------------------------------------------------------
Should use TestSuite rather than plain lua table

--------------------------------------------------------------------------------
luajit: …jason/torch/install/share/lua/5.1/torch/Tester.lua:362: An error was found while running tests!
stack traceback:
	[C]: in function 'assert'
	... jason/torch/install/share/lua/5.1/torch/Tester.lua:362: in function 'run'
	...ant/torch/install/share/lua/5.1/cltorch/unit_storage.lua:91: in function 'test'
	... jason/torch/install/share/lua/5.1/cltorch/Test.lua:8: in function 'test'
	(command line):1: in main chunk
	[C]: at 0x0102fc4bb0

Jasons-MacBook-Pro:~ jason$ th -l cltorch -e 'cltorch.about()'
cltorch.  OpenCL backend for Torch
Built from commit c45b2f0
More info, doc: https://github.com/hughperkins/cltorch
Issues: https://github.com/hughperkins/cltorch/issues

**Comment by hughperkins** [comment]
Hi Jason,

This should in theory be fixed in 61bb912b13  Can you pull latest version of cltorch, and retry pleaes?

Hugh
