### ISSUE TITLE
cltorch not linking properly

### ISSUE THREAD

**Issue by ultrons** [hughperkins/cltorch#63]
Hi,

I think it's something very silly, but I could not find it.
I am trying to run the test suite after the installation, I get following error.

>....$ luajit -l cltorch -e 'cltorch.test()'
running tests...
luajit: ...ICK/torch/install/share/lua/5.1/cltorch/unit_storage.lua:80: attempt to call field 'TestSuite' (a nil value)
stack traceback:
	...ICK/torch/install/share/lua/5.1/cltorch/unit_storage.lua:80: in main chunk
	[C]: in function 'require'
	...rs/MAVERICK/torch/install/share/lua/5.1/cltorch/Test.lua:5: in function 'test'
	(command line):1: in main chunk
	[C]: at 0x0107482ff0

.>..$ th -l cltorch -e 'cltorch.about()'
cltorch.  OpenCL backend for Torch
Built from commit 2df6d99
More info, doc: https://github.com/hughperkins/cltorch
Issues: https://github.com/hughperkins/cltorch/issues

I am using OS X, version 10.11.

I have also created the link in ~/lib, as given in the instruction. Here is what ~/lib contains (sorry for this verbose tree, pasting just in case any pre-req is missing):

/Users/MAVERICK/lib
├── EasyCL
│   ├── EasyCL-targets-relwithdebinfo.cmake
│   └── EasyCL-targets.cmake
├── cmake
│   └── clBLAS
│       ├── clBLASConfig.cmake
│       ├── clBLASConfigVersion.cmake
│       ├── clBLASTargets-relwithdebinfo.cmake
│       └── clBLASTargets.cmake
├── libEasyCL.dylib
├── libTH.dylib
├── libTHCl.dylib
├── libclBLAS.2.11.0.dylib
├── libclBLAS.2.dylib -> libclBLAS.2.11.0.dylib
├── libclBLAS.dylib -> libclBLAS.2.dylib
├── libclew.1.0.0.dylib
├── libclew.1.dylib -> libclew.1.0.0.dylib
├── libclew.dylib -> libclew.1.dylib
├── libluaT.dylib
├── libluajit.dylib
├── libqlua.dylib
├── libqtlua.dylib
├── lua
│   └── 5.1
│       ├── base64.so
│       ├── cjson.so
│       ├── crypto.so
│       ├── ffi.so
│       ├── lfs.so
│       ├── libTHCLNN.so
│       ├── libTHNN.so
│       ├── libclnn.so
│       ├── libcltorch.so
│       ├── libimage.so
│       ├── libjpeg.so
│       ├── libloadcaffe.so
│       ├── libnnx.so
│       ├── libpaths.so
│       ├── libpng.so
│       ├── libppm.so
│       ├── libqtcore.so
│       ├── libqtgui.so
│       ├── libqtide.so
│       ├── libqtsvg.so
│       ├── libqttorch.so
│       ├── libqtuiloader.so
│       ├── libqtwidget.so
│       ├── libsignal.so
│       ├── libsundown.so
│       ├── libsys.so
│       ├── libthreads.so
│       ├── libtorch.so
│       ├── lzmq
│       │   └── timer.so
│       ├── lzmq.so
│       ├── readline.so
│       └── treplutils.so
└── luarocks
    └── rocks
        ├── argcheck
        │   └── scm-1
        │       ├── argcheck-scm-1.rockspec
        │       ├── doc
        │       │   └── tree.png
        │       └── rock_manifest
        ├── clnn
        │   └── scm-1
        │       ├── clnn-scm-1.rockspec
        │       ├── doc
        │       │   ├── cunn
        │       │   │   └── nn-operators.md
        │       │   ├── older-changes.md
        │       │   └── porting-guidelines.md
        │       └── rock_manifest
        ├── cltorch
        │   └── scm-1
        │       ├── cltorch-scm-1.rockspec
        │       ├── doc
        │       │   ├── ContributorGuidelines.md
        │       │   ├── ImplementedDetails.md
        │       │   ├── MigrateStatusByFile.md
        │       │   ├── OlderChanges.md
        │       │   ├── img
        │       │   │   ├── gpupipelinemultiple.png
        │       │   │   ├── reduceall_pipelinestall.png
        │       │   │   └── singlegpuoperation.png
        │       │   └── torch
        │       │       ├── cuda-to-opencl.md
        │       │       ├── cutorch-apply.md
        │       │       └── torch.md
        │       └── rock_manifest
        ├── cwrap
        │   └── scm-1
        │       ├── cwrap-scm-1.rockspec
        │       ├── doc
        │       │   ├── argumenttypes.md
        │       │   ├── example.md
        │       │   ├── highlevelinterface.md
        │       │   ├── index.md
        │       │   └── usertypes.md
        │       └── rock_manifest
        ├── dok
        │   └── scm-1
        │       ├── dok-scm-1.rockspec
        │       └── rock_manifest
        ├── env
        │   └── scm-1
        │       ├── env-scm-1.rockspec
        │       └── rock_manifest
        ├── fftw3
        │   └── scm-1
        │       ├── doc
        │       │   ├── LICENSE
        │       │   └── README.md
        │       ├── fftw3-scm-1.rockspec
        │       └── rock_manifest
        ├── gnuplot
        │   └── scm-1
        │       ├── doc
        │       │   ├── common.md
        │       │   ├── custom.md
        │       │   ├── file.md
        │       │   ├── index.md
        │       │   ├── plot3dpoints.md
        │       │   ├── plot_filled.png
        │       │   ├── plot_hist.png
        │       │   ├── plot_imagesc.png
        │       │   ├── plot_raw.png
        │       │   ├── plot_sincos.png
        │       │   ├── plot_splot.png
        │       │   ├── plot_splot2.png
        │       │   ├── plot_x.png
        │       │   ├── plot_xyf.png
        │       │   ├── plothistogram.md
        │       │   ├── plotline.md
        │       │   ├── plotmatrix.md
        │       │   ├── plotsurface.md
        │       │   ├── scatter3.png
        │       │   └── scatter3_helix.png
        │       ├── gnuplot-scm-1.rockspec
        │       └── rock_manifest
        ├── graph
        │   └── scm-1
        │       ├── doc
        │       │   └── README.md
        │       ├── graph-scm-1.rockspec
        │       └── rock_manifest
        ├── graphicsmagick
        │   └── 1.scm-0
        │       ├── doc
        │       │   └── README.md
        │       ├── graphicsmagick-1.scm-0.rockspec
        │       └── rock_manifest
        ├── image
        │   └── 1.1.alpha-0
        │       ├── doc
        │       │   ├── colorspace.md
        │       │   ├── gui.md
        │       │   ├── index.md
        │       │   ├── paramtransform.md
        │       │   ├── saveload.md
        │       │   ├── simpletransform.md
        │       │   └── tensorconstruct.md
        │       ├── image-1.1.alpha-0.rockspec
        │       └── rock_manifest
        ├── itorch
        │   └── scm-1
        │       ├── doc
        │       │   ├── LICENSE
        │       │   └── README.md
        │       ├── itorch-scm-1.rockspec
        │       └── rock_manifest
        ├── lbase64
        │   └── 20120820-1
        │       ├── doc
        │       │   └── README
        │       ├── lbase64-20120820-1.rockspec
        │       └── rock_manifest
        ├── loadcaffe
        │   └── 1.0-0
        │       ├── doc
        │       │   ├── LICENSE
        │       │   └── README.md
        │       ├── loadcaffe-1.0-0.rockspec
        │       └── rock_manifest
        ├── lua-cjson
        │   └── 2.1.0-1
        │       ├── bin
        │       │   ├── json2lua
        │       │   └── lua2json
        │       ├── lua-cjson-2.1.0-1.rockspec
        │       ├── rock_manifest
        │       └── tests
        │           ├── README
        │           ├── bench.lua
        │           ├── example1.json
        │           ├── example2.json
        │           ├── example3.json
        │           ├── example4.json
        │           ├── example5.json
        │           ├── genutf8.pl
        │           ├── numbers.json
        │           ├── octets-escaped.dat
        │           ├── rfc-example1.json
        │           ├── rfc-example2.json
        │           ├── test.lua
        │           └── types.json
        ├── luacrypto
        │   └── 0.3.2-1
        │       ├── doc
        │       │   ├── Makefile.am
        │       │   ├── Makefile.in
        │       │   └── us
        │       │       ├── examples.html
        │       │       ├── index.html
        │       │       ├── license.html
        │       │       ├── luacrypto-128.png
        │       │       └── manual.html
        │       ├── luacrypto-0.3.2-1.rockspec
        │       └── rock_manifest
        ├── luaffi
        │   └── scm-1
        │       ├── doc
        │       │   ├── LICENSE
        │       │   └── README.md
        │       ├── luaffi-scm-1.rockspec
        │       └── rock_manifest
        ├── luafilesystem
        │   └── 1.6.3-1
        │       ├── doc
        │       │   └── us
        │       │       ├── doc.css
        │       │       ├── examples.html
        │       │       ├── index.html
        │       │       ├── license.html
        │       │       ├── luafilesystem.png
        │       │       └── manual.html
        │       ├── luafilesystem-1.6.3-1.rockspec
        │       ├── rock_manifest
        │       └── tests
        │           └── test.lua
        ├── lzmq
        │   └── 0.4.3-1
        │       ├── examples
        │       │   ├── device
        │       │   │   ├── cli.lua
        │       │   │   ├── device.lua
        │       │   │   └── srv.lua
        │       │   ├── echo_cli.lua
        │       │   ├── echo_loop.lua
        │       │   ├── echo_loop_raw.lua
        │       │   ├── monitor.lua
        │       │   ├── perf
        │       │   │   ├── local_lat.lua
        │       │   │   ├── local_multipart.lua
        │       │   │   ├── local_thr.lua
        │       │   │   ├── remote_lat.lua
        │       │   │   ├── remote_multipart.lua
        │       │   │   ├── remote_thr.lua
        │       │   │   ├── test_lat.bat
        │       │   │   ├── test_multipart.bat
        │       │   │   ├── test_thr.bat
        │       │   │   ├── thread_lat.lua
        │       │   │   └── thread_thr.lua
        │       │   ├── perf2
        │       │   │   ├── lat
        │       │   │   │   ├── inproc_lat.lua
        │       │   │   │   ├── local_lat.lua
        │       │   │   │   └── remote_lat.lua
        │       │   │   ├── lat_nomsg
        │       │   │   │   ├── inproc_lat.lua
        │       │   │   │   ├── local_lat.lua
        │       │   │   │   └── remote_lat.lua
        │       │   │   ├── runner.lua
        │       │   │   ├── thr
        │       │   │   │   ├── inproc_thr.lua
        │       │   │   │   ├── local_thr.lua
        │       │   │   │   └── remote_thr.lua
        │       │   │   └── thr_nomsg
        │       │   │       ├── inproc_thr.lua
        │       │   │       ├── local_thr.lua
        │       │   │       └── remote_thr.lua
        │       │   ├── queue_device.lua
        │       │   ├── utils.lua
        │       │   ├── uv_actor.lua
        │       │   └── zap.lua
        │       ├── lzmq-0.4.3-1.rockspec
        │       ├── rock_manifest
        │       └── test
        │           ├── lunit
        │           │   └── console.lua
        │           ├── test.lua
        │           ├── test_metadata.lua
        │           ├── test_proxy.lua
        │           ├── test_req_relaxed.lua
        │           ├── test_threads.lua
        │           ├── test_threads_actor.lua
        │           ├── test_threads_actor_poll.lua
        │           ├── test_threads_arg.lua
        │           ├── test_threads_file.lua
        │           ├── test_threads_fork.lua
        │           ├── test_threads_fork_arg.lua
        │           ├── test_threads_fork_opt.lua
        │           ├── test_threads_opt.lua
        │           ├── test_threads_sync.lua
        │           ├── thread.lua
        │           └── utest.lua
        ├── manifest
        ├── nn
        │   └── scm-1
        │       ├── doc
        │       │   ├── containers.md
        │       │   ├── convolution.md
        │       │   ├── criterion.md
        │       │   ├── image
        │       │   │   ├── abs.png
        │       │   │   ├── elu.png
        │       │   │   ├── exp.png
        │       │   │   ├── hshrink.png
        │       │   │   ├── htanh.png
        │       │   │   ├── lena.jpg
        │       │   │   ├── lenap.jpg
        │       │   │   ├── logsigmoid.png
        │       │   │   ├── logsoftmax.png
        │       │   │   ├── power.png
        │       │   │   ├── prelu.png
        │       │   │   ├── relu.png
        │       │   │   ├── rrelu.png
        │       │   │   ├── sigmmoid.png
        │       │   │   ├── sigmoid.png
        │       │   │   ├── softmax.png
        │       │   │   ├── softmin.png
        │       │   │   ├── softplus.png
        │       │   │   ├── softsign.png
        │       │   │   ├── sqrt.png
        │       │   │   ├── square.png
        │       │   │   ├── sshrink.png
        │       │   │   └── tanh.png
        │       │   ├── index.md
        │       │   ├── module.md
        │       │   ├── overview.md
        │       │   ├── simple.md
        │       │   ├── table.md
        │       │   ├── testing.md
        │       │   ├── training.md
        │       │   └── transfer.md
        │       ├── nn-scm-1.rockspec
        │       └── rock_manifest
        ├── nngraph
        │   └── scm-1
        │       ├── doc
        │       │   ├── annotation_bg.png
        │       │   ├── annotation_fg.png
        │       │   ├── mlp.png
        │       │   ├── mlp2.png
        │       │   ├── mlp3_backward.png
        │       │   ├── mlp3_forward.png
        │       │   ├── mlp4_backward.png
        │       │   ├── mlp4_forward.png
        │       │   └── my_bad_linear_net.png
        │       ├── nngraph-scm-1.rockspec
        │       └── rock_manifest
        ├── nnx
        │   └── 0.1-1
        │       ├── doc
        │       │   └── image
        │       │       ├── Lenna-150x150-bilinear.png
        │       │       └── Lenna.png
        │       ├── nnx-0.1-1.rockspec
        │       └── rock_manifest
        ├── optim
        │   └── 1.0.5-0
        │       ├── doc
        │       │   └── index.md
        │       ├── optim-1.0.5-0.rockspec
        │       └── rock_manifest
        ├── paths
        │   └── scm-1
        │       ├── doc
        │       │   ├── dirfunctions.md
        │       │   ├── dirpaths.md
        │       │   ├── filenames.md
        │       │   ├── index.md
        │       │   └── misc.md
        │       ├── paths-scm-1.rockspec
        │       └── rock_manifest
        ├── penlight
        │   └── 1.3.2-2
        │       ├── doc
        │       │   └── LICENSE.md
        │       ├── penlight-1.3.2-2.rockspec
        │       └── rock_manifest
        ├── qtlua
        │   └── scm-1
        │       ├── conf
        │       │   └── cmake
        │       │       └── QtLuaConfig.cmake
        │       ├── doc
        │       │   ├── index.md
        │       │   ├── qt.md
        │       │   ├── qtcore.md
        │       │   ├── qtgui.md
        │       │   ├── qtide.md
        │       │   ├── qtsvg.md
        │       │   ├── qtuiloader.md
        │       │   └── qtwidget.md
        │       ├── qtlua-scm-1.rockspec
        │       └── rock_manifest
        ├── qttorch
        │   └── scm-1
        │       ├── doc
        │       │   └── README.md
        │       ├── qttorch-scm-1.rockspec
        │       └── rock_manifest
        ├── signal
        │   └── scm-1
        │       ├── doc
        │       │   ├── _highlight
        │       │   │   ├── LICENSE
        │       │   │   ├── README.md
        │       │   │   ├── classref.txt
        │       │   │   ├── highlight.pack.js
        │       │   │   └── styles
        │       │   │       ├── arta.css
        │       │   │       ├── ascetic.css
        │       │   │       ├── brown_paper.css
        │       │   │       ├── brown_papersq.png
        │       │   │       ├── dark.css
        │       │   │       ├── default.css
        │       │   │       ├── docco.css
        │       │   │       ├── far.css
        │       │   │       ├── foundation.css
        │       │   │       ├── github.css
        │       │   │       ├── googlecode.css
        │       │   │       ├── idea.css
        │       │   │       ├── ir_black.css
        │       │   │       ├── magula.css
        │       │   │       ├── mono-blue.css
        │       │   │       ├── monokai.css
        │       │   │       ├── monokai_sublime.css
        │       │   │       ├── obsidian.css
        │       │   │       ├── pojoaque.css
        │       │   │       ├── pojoaque.jpg
        │       │   │       ├── railscasts.css
        │       │   │       ├── rainbow.css
        │       │   │       ├── school_book.css
        │       │   │       ├── school_book.png
        │       │   │       ├── solarized_dark.css
        │       │   │       ├── solarized_light.css
        │       │   │       ├── sunburst.css
        │       │   │       ├── tomorrow-night-blue.css
        │       │   │       ├── tomorrow-night-bright.css
        │       │   │       ├── tomorrow-night-eighties.css
        │       │   │       ├── tomorrow-night.css
        │       │   │       ├── tomorrow.css
        │       │   │       ├── vs.css
        │       │   │       ├── xcode.css
        │       │   │       └── zenburn.css
        │       │   ├── _markdown
        │       │   │   └── signal
        │       │   │       ├── README.md
        │       │   │       ├── complex.md
        │       │   │       ├── convolution.md
        │       │   │       ├── extramath.md
        │       │   │       ├── ffi.md
        │       │   │       ├── fft.md
        │       │   │       ├── init.md
        │       │   │       └── wavelet.md
        │       │   ├── index.html
        │       │   ├── search.js
        │       │   ├── signal
        │       │   │   ├── complex.html
        │       │   │   ├── convolution.html
        │       │   │   ├── extra
        │       │   │   │   └── README.html
        │       │   │   ├── extramath.html
        │       │   │   ├── ffi.html
        │       │   │   ├── fft.html
        │       │   │   ├── index.html
        │       │   │   ├── init.html
        │       │   │   ├── style.css
        │       │   │   └── wavelet.html
        │       │   ├── style-page.css
        │       │   └── style.css
        │       ├── rock_manifest
        │       └── signal-scm-1.rockspec
        ├── sundown
        │   └── scm-1
        │       ├── bin
        │       │   └── mdcat
        │       ├── doc
        │       │   ├── LICENSE.md
        │       │   └── README.md
        │       ├── rock_manifest
        │       └── sundown-scm-1.rockspec
        ├── sys
        │   └── 1.1-0
        │       ├── doc
        │       │   ├── LICENSE
        │       │   └── README.md
        │       ├── rock_manifest
        │       └── sys-1.1-0.rockspec
        ├── threads
        │   └── scm-1
        │       ├── doc
        │       │   └── README.md
        │       ├── rock_manifest
        │       └── threads-scm-1.rockspec
        ├── torch
        │   └── scm-1
        │       ├── doc
        │       │   ├── cmdline.md
        │       │   ├── diskfile.md
        │       │   ├── file.md
        │       │   ├── gather.png
        │       │   ├── index.md
        │       │   ├── maths.md
        │       │   ├── memoryfile.md
        │       │   ├── pipefile.md
        │       │   ├── random.md
        │       │   ├── serialization.md
        │       │   ├── storage.md
        │       │   ├── tensor.md
        │       │   ├── tester.md
        │       │   ├── timer.md
        │       │   └── utility.md
        │       ├── rock_manifest
        │       └── torch-scm-1.rockspec
        ├── trepl
        │   └── scm-1
        │       ├── bin
        │       │   └── th
        │       ├── doc
        │       │   └── index.md
        │       ├── rock_manifest
        │       └── trepl-scm-1.rockspec
        ├── uuid
        │   └── 0.2-1
        │       ├── doc
        │       │   ├── index.html
        │       │   ├── ldoc.css
        │       │   └── topics
        │       │       └── readme.md.html
        │       ├── rock_manifest
        │       └── uuid-0.2-1.rockspec
        └── xlua
            └── 1.0-0
                ├── doc
                │   └── README.md
                ├── rock_manifest
                └── xlua-1.0-0.rockspec

Thanks a lot for your help.

**Comment by hughperkins** [comment]
Hmmm, might be an old version of torch.  Can you try the following ,see if it changes anything pleaes?
```
luarocks install torch
```

**Comment by ultrons** [comment]
Thanks for your super quick reply
Indeed older version of LUA was causing this.
I ran "luarocks install torch" and the test suite works like charm :)

**Comment by hughperkins** [comment]
Ok cool :-)
