### ISSUE TITLE
Memory leak when calling :set()

### ISSUE THREAD

**Issue by fmassa** [hughperkins/cltorch#64]
Follow up on the bug mentioned on https://github.com/szagoruyko/cifar.torch/pull/17#issuecomment-210494811

The bug with `clearState` is in [here](https://github.com/hughperkins/cltorch/blob/master/src/lib/THClTensor.cpp#L644-L656) I think. Compare it to the [cutorch version](https://github.com/torch/cutorch/blob/master/lib/THC/generic/THCTensor.c#L643-L655). Basically in torch, if we call `tensor:set()` (without arguments) it frees the storage of `tensor`. In your case you only free it if the provided argument has non-null storage.

**Comment by hughperkins** [comment]
Whoa, nice spot :-O  That works perfectly :-)  That would have taken me forever to find.  I thought it was a bug in my network modules, and would have spent hours digging out wondering why hacking around in the network modules wasnt fixing anything :-D

Thank you very much.  Awesome! :-)

**Comment by fmassa** [comment]
Great ! Glad I could be helpful ! :)
