### ISSUE TITLE
I have multiple GPU, why test-device.lua only see 1

### ISSUE THREAD

**Issue by mingwugmail** [hughperkins/cltorch#74]
$ lspci 

01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii PRO [Radeon R9 290]
02:00.0 VGA compatible controller: NVIDIA Corporation GM206 [GeForce GTX 960](rev a1)

$ luajit -l cltorch  ./src/test/test-device.lua
running require cltorch...
... require cltorch done
num devices:    1
device properties, device   1
    deviceType  GPU
    localMemSizeKB  48
    globalMemSizeMB 4095
    deviceVersion   OpenCL 1.2 CUDA
    platformVendor  NVIDIA Corporation
    deviceName  GeForce GTX 960
    maxComputeUnits 8
    globalMemCachelineSizeKB    0
    openClCVersion  OpenCL C 1.2 
    maxClockFrequency   1367
    maxMemAllocSizeMB   1023
    maxWorkGroupSize    1024
Using NVIDIA Corporation , OpenCL platform: NVIDIA CUDA
Using OpenCL device: GeForce GTX 960
c1
     7
-4
 5
[torch.ClTensor of size 3]

 7
 4
 5
[torch.ClTensor of size 3]

Thanks.

**Comment by hughperkins** [comment]
Hi Mingwu,

Normally it will probably be because the OpenCL drivers for that GPU have not been installed.  Can you provide the output of `clinfo` please?  (You might need to `sudo apt-get install clinfo` first)

**Comment by mingwugmail** [comment]
$ sudo clinfo
[sudo] password for zhou: 
Number of platforms:				 2
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 1.2 CUDA 7.5.23
  Platform Name:				 NVIDIA CUDA
  Platform Vendor:				 NVIDIA Corporation
  Platform Extensions:				 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts 
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (1598.5)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 


  Platform Name:				 NVIDIA CUDA
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 10deh
  Max compute units:				 8
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 64
  Max work group size:				 1024
  Preferred vector width char:			 1
  Preferred vector width short:			 1
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 1
  Native vector width short:			 1
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 1367Mhz
  Address bits:					 64
  Max memory allocation:			 1073692672
  Image support:				 Yes
  Max number of images read arguments:		 256
  Max number of images write arguments:		 16
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 4096
  Max image 3D height:				 4096
  Max image 3D depth:				 4096
  Max samplers within kernel:			 32
  Max size of kernel argument:			 4352
  Alignment (bits) of base address:		 4096
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 128
  Cache size:					 131072
  Global memory size:				 4294770688
  Constant buffer size:				 65536
  Max number of constant args:			 9
  Local memory type:				 Scratchpad
  Local memory size:				 49152
  Kernel Preferred work group size multiple:	 32
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1000
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 0x23e2650
  Name:						 GeForce GTX 960
  Vendor:					 NVIDIA Corporation
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 352.79
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 CUDA
  Extensions:					 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts  cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 


  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 2
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 
  Device Topology:				 PCI[ B#1, D#0, F#0 ]
  Max compute units:				 40
  Max work items dimensions:			 3
    Max work items[0]:				 256
    Max work items[1]:				 256
    Max work items[2]:				 256
  Max work group size:				 256
  Preferred vector width char:			 4
  Preferred vector width short:			 2
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 4
  Native vector width short:			 2
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 947Mhz
  Address bits:					 64
  Max memory allocation:			 3006529536
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 64
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 2048
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 No
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 4248829952
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 32768
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 3006529536
  Max global variable size:			 3006529536
  Max global variable preferred total size:	 4248829952
  Max read/write image args:			 64
  Max on device events:				 1024
  Queue on device max size:			 262144
  Max on device queues:				 1
  Queue on device preferred size:		 16384
  SVM capabilities:				 
    Coarse grain buffer:			 Yes
    Fine grain buffer:				 No
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 64
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 0x7ff0428b5670
  Name:						 Hawaii
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 1598.5 (VM)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 2.0 AMD-APP (1598.5)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_atomic_counters_32 cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images 


  Device Type:					 CL_DEVICE_TYPE_CPU
  Vendor ID:					 1002h
  Board name:					 
  Max compute units:				 8
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 1024
  Max work group size:				 1024
  Preferred vector width char:			 16
  Preferred vector width short:			 8
  Preferred vector width int:			 4
  Preferred vector width long:			 2
  Preferred vector width float:			 8
  Preferred vector width double:		 4
  Native vector width char:			 16
  Native vector width short:			 8
  Native vector width int:			 4
  Native vector width long:			 2
  Native vector width float:			 8
  Native vector width double:			 4
  Max clock frequency:				 1400Mhz
  Address bits:					 64
  Max memory allocation:			 4201179136
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 64
  Max image 2D width:				 8192
  Max image 2D height:				 8192
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 4096
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 16804716544
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Global
  Local memory size:				 32768
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 4201179136
  Max global variable size:			 1879048192
  Max global variable preferred total size:	 1879048192
  Max read/write image args:			 64
  Max on device events:				 0
  Queue on device max size:			 0
  Max on device queues:				 0
  Queue on device preferred size:		 0
  SVM capabilities:				 
    Coarse grain buffer:			 Yes
    Fine grain buffer:				 Yes
    Fine grain system:				 Yes
    Atomics:					 Yes
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 1
  Error correction support:			 0
  Unified memory for Host and Device:		 1
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 Yes
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 No
    Profiling :					 No
  Platform ID:					 0x7ff0428b5670
  Name:						 AMD FX(tm)-8320 Eight-Core Processor
  Vendor:					 AuthenticAMD
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 1598.5 (sse2,avx,fma4)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 AMD-APP (1598.5)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_spir cl_khr_gl_event 

========================

it shows:

  Name:						 Hawaii

**Comment by mingwugmail** [comment]
BTW, I'm 'ssh -X' into that machine, and running with 'sudo'.

Does it matter?

**Comment by mingwugmail** [comment]
Indeed I need to run with 'sudo su', and then it can see 2 GPUs.

# luajit -l cltorch ./src/test/test-device.lua
running require cltorch...
... require cltorch done
num devices:	2
device properties, device	1
   	deviceType	GPU
   	localMemSizeKB	48
   	globalMemSizeMB	4095
   	deviceVersion	OpenCL 1.2 CUDA
   	platformVendor	NVIDIA Corporation
   	deviceName	GeForce GTX 960
   	maxComputeUnits	8
   	globalMemCachelineSizeKB	0
   	openClCVersion	OpenCL C 1.2 
   	maxClockFrequency	1367
   	maxMemAllocSizeMB	1023
   	maxWorkGroupSize	1024
device properties, device	2
   	deviceType	GPU
   	localMemSizeKB	32
   	globalMemSizeMB	4052
   	deviceVersion	OpenCL 2.0 AMD-APP (1598.5)
   	platformVendor	Advanced Micro Devices, Inc.
   	deviceName	Hawaii
   	maxComputeUnits	40
   	globalMemCachelineSizeKB	0
   	openClCVersion	OpenCL C 2.0 
   	maxClockFrequency	947
   	maxMemAllocSizeMB	2867
   	maxWorkGroupSize	256
Using NVIDIA Corporation , OpenCL platform: NVIDIA CUDA
Using OpenCL device: GeForce GTX 960
c1
	 7
-4
 5
[torch.ClTensor of size 3]

 7
 4
 5
[torch.ClTensor of size 3]

Using Advanced Micro Devices, Inc. , OpenCL platform: AMD Accelerated Parallel Processing
Using OpenCL device: Hawaii
c1
	 7
-4
 5
[torch.ClTensor of size 3]

 7
 4
 5
[torch.ClTensor of size 3]

============================================
Now my question is why I can only run OpenCL on R290 as 'su'? but not as ordinary user?

Is there any way I can fix this?

Thanks.

**Comment by hughperkins** [comment]
> BTW, I'm 'ssh -X' into that machine, and running with 'sudo'.
>
> Does it matter?

Yes, probably.  GPU drivers in general tend to prefer one uses them from a desktop enviornment, which is using that GPU.  As far as I know, AMD GPUs are no less picky in this respect.  Unfortunately I dont have am AMD GPU to test with, and prevoius threads on the amd list, eg https://github.com/amd/OpenCL-caffe/issues/13 never seemed to get resolved.  I'm not really sure how to solve this to be honest.

For NVIDIA, on linux, it tends to be sufficient to just run with sudo.

For NVIDIA, on Windows, I find I have to use vnc to connect to the desktop (eg rdesktop doesnt work correctly, inserts some other driver into the video stack somehow).

Maybe you can try vnc perhaps???  The best thing would be to check with some support guy, but, there's a lot of AMD guys in that thread I just linked to, so ... ????

**Comment by mingwugmail** [comment]
Guess I have to use 'sudo su'.

The next question is how do I tell cltorch which GPU device to run?

**Comment by hughperkins** [comment]
> Guess I have to use 'sudo su'.

Cool.  If that works, thats excellent info :-)

> The next question is how do I tell cltorch which GPU device to run?

In theory it hsould be like:
```
cltorch.setDevice(2)
```
... for the second gpu, or:
```
cltorch.setDevice(1)
```
... for the first one

**Comment by mehditlili** [comment]
Just a small comment as I also was facing this problem.
First running scripts with sudo in linux is kind of unsafe.
I didn't test with Nvidia or AMD graphic cards but I had the same problem with Intel HD integrated graphics. The trick was to add the user to the group "video"
`sudo usermod -a -G video $LOGNAME`

and to close the ssh session and reconnect again. then clinfo displays your gpu with no need for sudo.

**Comment by gslin** [comment]
Although this issue is a little old, but I would like to add some notes.  Hope this can help others.

In my case /dev/kfd is `root:render` instead of `root:video`:

    crw-rw---- 1 root render 237, 0 Feb 26 15:15 /dev/kfd

So you would need to use `sudo usermod -a -G render $LOGNAME` to do this.
