### ISSUE TITLE
Can't get neural-style to work with this or distro-cl

### ISSUE THREAD

**Issue by slessie** [hughperkins/cltorch#76]
Started an issue at neural-style but jcjohnson got the same install fail. 
More info on the link
https://github.com/jcjohnson/neural-style/issues/246

Quick summary, I can run neural-style fine on cpu. When trying to use opencl to run, it fails even with a working install of distro-cl. 

jcjohnson suggested I use

luarocks install cltorch
luarocks install clnn

The install fails and says to install from distro-cl

**Comment by hughperkins** [comment]
Please run:
```
source ~/torch-cl/install/ bin/torch-activate
```
... and try again?

**Comment by slessie** [comment]
`source ~/torch-cl/install/ bin/torch-activate`

That along with also installing loadcaffe in the torch-cl directory worked.

**Comment by hughperkins** [comment]
Cool. awesome :-)  maybe I will just add loadcaffe to distro-cl.  It seems like it's a standard enough thing to simply add.  Will ponder this.  Thanks for figuring this out!
