### ISSUE TITLE
THClTensor_maskedSelect

### ISSUE THREAD

**Issue by ViliusT** [hughperkins/cltorch#77]
Hi hughperkins,

I've got an error when using cltorch:

`/home/-/torch-cl/install/bin/luajit: symbol lookup error: /home/-/torch-cl/install/lib/lua/5.1/libcltorch.so: undefined symbol: THClTensor_maskedSelect
`

I am currently moving the offending operations to :float() and then bringing them back to :cl(), but this quite slow, and I am hitting this problem quite often now (although I am not sure yet, I believe this might be due to using torch.resizeAs() method)

I noticed that THClTensor_maskedSelect is not implemented - since I lack the experience to implement it myself, I was wondering if there are any plans for its support on cltorch?

**Comment by hughperkins** [comment]
Hmmm....  well...  I'm currently working on convolution https://github.com/hughperkins/winogradcl-underconstruction ... but ... I cant probably look at this sometime, might not be right now this week or two though.

**Comment by hughperkins** [comment]
Implemented now :-)

**Comment by ViliusT** [comment]
Whoops, looks like I forgot to hit [Comment] button last time;

Thanks huhgperkins!
