### ISSUE TITLE
Opencl working, ish.

### ISSUE THREAD

**Issue by AWOLASAP** [hughperkins/cltorch#85]
I am training with Andrej Karpathy's char rnn, and whenever I use opencl to train, the integrated intel hd graphics gets used and not my amd radeon pro 560x

**Comment by mturlo** [comment]
Have you tried using the `-gpuid` (i.e. `-gpuid 2`) option?

**Comment by AWOLASAP** [comment]
I figured this out a bit ago and I fee kinda dumb, especially because I forgot I posted this. You need to use -opencl option and -gpuid option. Thanks mturlo for the comment.
